Timer additions: raw access to prescaler and auto-reload
stm32-rs/stm32f1xx-hal pull request #322
Opened 2021-03-18 01:00 UTC by Windfisch

I frequently use timers for precise measurements, and unfortunately, `start_countdown` performs intransparent calculations which can introduce rounding errors.

This PR adds the capability to set and read the raw prescaler and auto-reload values, also we can now read the timer's count; this is useful when ARR is set to `0xFFFF`, i.e. the timer is just "free-running".

2021-03-18 01:58 UTC, Windfisch commented
Hm, seems like it fails to build with `cargo check --features=stm32f100,rt` but works with `cargo check --features=stm32f100,rt`.

I don't understand why it gives me this error for stm32f100, but not for f103.
```
error[E0133]: call to unsafe function is unsafe and requires unsafe function or block
   --> src/timer.rs:366:44
    |
366 |                       self.tim.arr.write(|w| w.arr().bits(arr) );
    |                                              ^^^^^^^^^^^^^^^^^ call to unsafe function
```

I could just wrap around an `unsafe`, but I'd prefer discussing this first. Is this a bug in the stm32 crate or am I missing something? Please help.

2021-04-06 17:51 UTC, TheZoq2 commented
I think there are some inconsistencies between the different f1 variants which causes that unsafe thingy, we can probably add an `unsafe` block and accept the warning it will throw on the other versions

2021-04-06 17:58 UTC, TheZoq2 requested changes
Thanks for the PR and sorry for the review delay. I added a few notes which would be nice if they are addressed

2021-04-06 17:58 UTC, TheZoq2 commented on src/timer.rs
> +                    self.tim.arr.write(|w| w.arr().bits(arr) );
From the normal `start` function, add `unsafe` and a `#[allow(unused_unsafe)]` attribute to silence the warnings.

2021-04-06 17:58 UTC, TheZoq2 commented on src/timer.rs
> +                }
Could you make the old `start` function call this to avoid code duplication

2021-04-12 08:49 UTC, Windfisch commented
Just to give a update, I've seen your suggestions and will implement them later this week. Thanks for the help :)

2021-04-16 18:34 UTC, Windfisch commented
I've implemented your requested changes and merged with the current master. Hopefully everything is fine now :)

2021-04-17 02:51 UTC, burrbull commented
> merged with the current master

Don't merge master in PRs, you make commit history non-linear. Rebase only.

2021-04-17 11:14 UTC, Windfisch commented
Thanks for the hint, I've updated my PR.

It may be helpful to state "rebase over merge" somewhere in a contibutor's guidelines document, or just under the "Contributing" header of the README, since it is not an obvious thing to do; other projects prefer it the other way round. Or is there such a document which I failed to find?

2021-05-02 10:46 UTC, TheZoq2 commented
Great work! Adding a CONTRIBUTING document stating rebasing is prefered is a pretty good idea. Though I assume that tends to almost always be the case when working on PRs, and the debate is more often about wether or not to do the final "merge" as a rebase or true merge.

2021-05-02 10:46 UTC, merged