Do not enable UART DMA flags unconditionally
stm32-rs/stm32f1xx-hal pull request #336
Opened 2021-05-17 22:06 UTC by Windfisch

Fixes #334

I have not tested that code, though, so proceed with caution :)

2021-05-19 00:05 UTC, Windfisch commented
Updated as per https://github.com/stm32-rs/stm32f1xx-hal/issues/334#issuecomment-842916316.

2021-05-20 22:48 UTC, Windfisch commented
Renamed serial-dma `split` and i2c `free` functions to `release` as per https://github.com/stm32-rs/stm32f1xx-hal/issues/334#issuecomment-843724427.

2021-05-26 17:55 UTC, TheZoq2 requested changes
Thanks for the PR! I pointed out a few `mut`s which cause warnings, other than that I think this is ready to merge (possibly after testing on hw)

2021-05-26 17:55 UTC, TheZoq2 commented on src/serial.rs
>                  pub fn split(mut self) -> (Rx<$USARTX>, $dmarxch) {
Could you remove the `mut` here since it gives a warning now that self is just passed along?

2021-05-26 17:55 UTC, TheZoq2 commented on src/serial.rs
>                  pub fn split(mut self) -> (Tx<$USARTX>, $dmatxch) {
Remove mut here as well

2021-07-13 14:27 UTC, burrbull commented
cc @TeXitoi

2021-07-13 17:05 UTC, TeXitoi approved these changes

2021-07-13 17:09 UTC, merged

2021-07-13 17:13 UTC, burrbull commented
> @burrbull you want acces right to this repo?

It would be great.

2021-07-13 17:17 UTC, TeXitoi commented
I can't find how to add you to the stm32f1 team, looks like I don't have the right or I can't find the settings

2021-07-13 17:19 UTC, adamgreig commented
Previously only @therealprof was a maintainer for the stm32f1 team, but I've added you as well @TeXitoi, so you should be able to add new team members now.

2021-07-13 17:21 UTC, TeXitoi commented
Thanks, @burrbull added.

2021-07-13 17:26 UTC, burrbull commented
Thanks.